{{- if .Values.region=hwpoc }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <h1>Nginx Test Server </h1>
    <h2>You're using hwpoc k8s cluster</h2>
{{- end }}