{{- if .Values.persistence.enabled }}
{{- if (not .Values.gitlab.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab" . }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "gitlab.labels" . | indent 4 }}
    component: gitlab
spec:
  accessModes: 
    - {{ .Values.gitlab.accessMode }}
  resources:
    requests:
      storage: {{ .Values.gitlab.size }}
  {{- if $gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

