{{- if .Values.persistence.enabled }}
{{- if (not .Values.gitlab.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: gitlab
spec:
  accessModes: ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

