apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-mini.fullname" . }}
  labels:
{{ include "gitlab-mini.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 31443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
      nodePort: 31022
  selector:
    app.kubernetes.io/name: {{ include "gitlab-mini.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
