apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: {{ .Values.service.nodePort.http }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: {{ .Values.service.nodePort.https }}
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
      nodePort: {{ .Values.service.nodePort.ssh }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
