{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-data"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-etc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab.etc.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}

