apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgresql
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    tier: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    tier: postgres
