apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      tier: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        tier: redis
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis
          image: "{{ .Values.image.repository_redis }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/redis
            name: gitlab-redis
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
      - name: gitlab-redis
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-redis"
      {{- else }}
        emptyDir: {}
      {{- end }}