apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    tier: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    tier: redis
