{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim.data) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-data"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim.etc) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-etc"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab.etc.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}

