{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-redis"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.size }}
  {{- if .Values.gitlab.storageClass }}
    {{- if eq "-" .Values.gitlab.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.gitlab.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
