{{- if eq .Values.region "Huawei-CCE" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <h1>Nginx Test Server </h1>
    <h2>You're using Huawei-CCE k8s cluster</h2>
{{- end }}