{{- if eq .Values.region "Local-DC" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <h1>Nginx Test Server </h1>
    <h2>You're using Local k8s cluster</h2>
{{- end }}