apiVersion: v1
version: "13.0.6"
appVersion: "13.0.6"
description: A light weight gitlab for rancher catalogs
name: gitlab-light
icon: file://../gitlab.png

keywords:
- gitlab
- git

sources:
- https://github.com/zm1990s/demo-charts/

maintainers:
- name: zhangmin  
  email: zhangmin@rancher.com